// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOieuxYvZycPqKjnsZ4d5AAEQy1Q_WlmA',
    appId: '1:595083646967:web:2aa5540fe55aa8580540f2',
    messagingSenderId: '595083646967',
    projectId: 'twitch-clone-dd6d0',
    authDomain: 'twitch-clone-dd6d0.firebaseapp.com',
    storageBucket: 'twitch-clone-dd6d0.firebasestorage.app',
    measurementId: 'G-0ME138SQ9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQ3-1i-eiu87Tqi1u0wAEJzaf2F65oK8',
    appId: '1:595083646967:android:2d9bb8a678ab9bc80540f2',
    messagingSenderId: '595083646967',
    projectId: 'twitch-clone-dd6d0',
    storageBucket: 'twitch-clone-dd6d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWjlJvYFOVQoH_D-mdq3KIIfdWhRqnIcQ',
    appId: '1:595083646967:ios:d82e1172bbf7dceb0540f2',
    messagingSenderId: '595083646967',
    projectId: 'twitch-clone-dd6d0',
    storageBucket: 'twitch-clone-dd6d0.firebasestorage.app',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWjlJvYFOVQoH_D-mdq3KIIfdWhRqnIcQ',
    appId: '1:595083646967:ios:d82e1172bbf7dceb0540f2',
    messagingSenderId: '595083646967',
    projectId: 'twitch-clone-dd6d0',
    storageBucket: 'twitch-clone-dd6d0.firebasestorage.app',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOieuxYvZycPqKjnsZ4d5AAEQy1Q_WlmA',
    appId: '1:595083646967:web:f11ff2dae8f397a60540f2',
    messagingSenderId: '595083646967',
    projectId: 'twitch-clone-dd6d0',
    authDomain: 'twitch-clone-dd6d0.firebaseapp.com',
    storageBucket: 'twitch-clone-dd6d0.firebasestorage.app',
    measurementId: 'G-2TLPPZZXD5',
  );

}